#!/usr/bin/env python3
"""Generate the config block of site/app.js from Config/github-config.json.

Usage:
  python3 scripts/generate-site-config.py [--check]

--check exits non-zero when site/app.js is out of date.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "Config" / "github-config.json"
APP_JS_PATH = ROOT / "site" / "app.js"
BEGIN = "  // BEGIN CONFIG (generated by scripts/generate-site-config.py)"
END = "  // END CONFIG"


def load_config() -> dict:
    with CONFIG_PATH.open() as f:
        return json.load(f)


def render_block(config: dict) -> str:
    hosts = ", ".join(json.dumps(h) for h in config["allowed_download_hosts"])
    return (
        BEGIN + "\n"
        + f"  var fallbackDownloadURL =\n    {json.dumps(config['fallback_download_url'])};\n"
        + f"  var expectedRepository = {json.dumps(config['expected_repository'])};\n"
        + f"  var allowedDownloadHosts = [{hosts}];\n"
        + f"  var githubAPIBase = {json.dumps(config['github_api_base'])};\n"
        + END
    )


def apply(content: str, block: str) -> str:
    start = content.index(BEGIN)
    end = content.index(END, start) + len(END)
    return content[:start] + block + content[end:]


def main() -> int:
    config = load_config()
    block = render_block(config)
    content = APP_JS_PATH.read_text()

    if BEGIN not in content or END not in content:
        sys.stderr.write(f"{APP_JS_PATH}: config markers not found\n")
        return 1

    updated = apply(content, block)
    if "--check" in sys.argv:
        if updated != content:
            sys.stderr.write(
                f"{APP_JS_PATH} is out of date. Run scripts/generate-site-config.py.\n"
            )
            return 1
        return 0

    APP_JS_PATH.write_text(updated)
    print(f"Updated {APP_JS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
